# Generated by Django 4.2.23 on 2025-08-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Sem título', max_length=100, unique=True)),
                ('genero', models.CharField(default='Sem genero', max_length=100, unique=True)),
                ('ano_lancamento', models.IntegerField()),
                ('descricao', models.TextField(default='sem descrição', max_length=500)),
                ('diretor', models.CharField(max_length=100)),
            ],
        ),
    ]
