# Generated by Django 4.2.23 on 2025-08-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_filme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='descricao',
            field=models.TextField(default='Sem Descrição', max_length=500),
        ),
        migrations.AlterField(
            model_name='filme',
            name='genero',
            field=models.CharField(choices=[('acao', 'Ação'), ('aventura', 'Aventura'), ('misterio', 'Mistério')], max_length=50),
        ),
        migrations.AlterField(
            model_name='filme',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
